myblog/blogApp/urls.py
from django.conf.urls import patterns, url
from . import  views
app_name = 'blog'
urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^(?P<post_id>\d+)/$', views.detail, name='detail'),
    url(r'^add_post/$', views.add_post, name= 'add_post'),
    url(r'^successful/$',views.success, name = 'successful')

]

myblog/myblog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from rest_framework import routers
from blogApp.views import PostViewSet, CommentsViewSet

router = routers.DefaultRouter()
router.register(r'post', PostViewSet)
router.register(r'comments',CommentsViewSet)

urlpatterns = [
    url(r'^v1.0/', include(router.urls)),
    url(r'^blogApp/', include('blogApp.urls')),
    url(r'^admin/', admin.site.urls),

]

myblog/blogApp/models.py
from __future__ import unicode_literals
from django.db import models


class BlogPost(models.Model):
    post_head = models.CharField("Head",max_length=150)
    post_text = models.CharField(max_length=10000)
    post_date = models.DateTimeField('date published')
    post_author = models.CharField(max_length=20)
    post_condition = models.BooleanField(default= False)

    def __unicode__(self):
        return self.post_head


class Comments(models.Model):
    comment_text = models.CharField(max_length=500)
    comment_author = models.CharField(max_length=20)
    comment_date = models.DateTimeField('comment date')
    post = models.ForeignKey(BlogPost, on_delete=models.CASCADE)

    def __unicode__(self):
        return self.comment_text

myblog/blogApp/forms.py
# coding: utf-8
from django import forms
from .models import Comments, BlogPost

class CommentsForm (forms.ModelForm):
    class Meta:
        model = Comments
        fields = ('comment_author','comment_text',)

class PostForm (forms.ModelForm):

    class Meta:
        model = BlogPost
        fields = ('post_head','post_author','post_text',)
        widgets = {"post_text": forms.widgets.Textarea(attrs={'rows': 2})}

myblog/blogApp/views.py
from django.http import Http404
from django.template import RequestContext
from django.shortcuts import render, render_to_response
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .forms import  CommentsForm,PostForm
import  datetime
from django.shortcuts import redirect
# Create your views here.

from .models import BlogPost, Comments
from serializers import PostSerializer,CommentsSerializer
from rest_framework import viewsets


class PostViewSet (viewsets.ModelViewSet):
    queryset = BlogPost.objects.all().order_by('-post_date')
    serializer_class = PostSerializer


class CommentsViewSet (viewsets.ModelViewSet):
    queryset = Comments.objects.all()
    serializer_class = CommentsSerializer



def index(request):
    '''Show posts'''
    posts_list = BlogPost.objects.filter(post_condition = True).order_by('-post_date')
    paginator = Paginator(posts_list, 10)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    vars = dict(posts=posts)
    return render_to_response('blogApp/index.html', vars, context_instance=RequestContext(request))


def detail (request, post_id):
    try:
        this_post = BlogPost.objects.get(pk=post_id,post_condition = True)
    except BlogPost.DoesNotExists:
        raise Http404('Post does not exist')
    this_comments = Comments.objects.filter(post=this_post)
    if request.method == "POST":
        form = CommentsForm(request.POST)
        if form.is_valid():
            new_commint = form.save(commit= False)
            new_commint.comment_date = datetime.datetime.now()
            new_commint.post_id = post_id
            new_commint.save()
            return redirect("blog:detail", post_id)
    else:
        form = CommentsForm()
    return render(request, 'blogApp/detail.html', {'this_post': this_post, 'this_comments': this_comments,'form': form})


def add_post(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            new_post = form.save(commit = False)
            new_post.post_date = datetime.datetime.now()
            new_post.save()
            return  redirect("blog:successful" )
    else:
        form = PostForm()
    return render(request, 'blogApp/add_post.html',{'form':form})


def success(request):
    return render(request,'blogApp/successful.html')

myblog/blogApp/templates/blogApp/add_post.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'blogApp/bootstrap.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'blogApp/jquery-3.0.0.min.js' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'blogApp/bootstrap-theme.min.css' %}" />
<html>

<nav class="navbar navbar-inverse">
<ul class="nav navbar-nav">
  <li role="presentation"><a href="{% url 'blog:index' %}">Home</a></li>
  <li role="presentation" class="active"><a href="{%url 'blog:add_post' %}">Add Post</a></li>
</ul>
</nav>

{% block content %}
<form method="post" class="post-form">{% csrf_token %}

    <!--{{form.as_p}}-->
   <div class="form-group col-md-10">
    <label for="id_post_head">{{form.post_head.label}}</label>
    <input type="text" id='id_post_head' name="post_head" class="form-control"  placeholder="{{form.post_head.label}}" >
  </div>


    <div class="form-group col-md-10">
    <label for="id_post_author">{{form.post_author.label}}</label>
    <input type="text" id='id_post_author' name="post_author" class="form-control"  placeholder="{{form.post_author.label}}" >
  </div>

    <div class="form-group col-md-10">
    <label>{{form.post_text.label}}</label>
        <!--<input type="text" id='{{form.post_text.label}}' name="{{form.post_text.label}}"class="form-control"  placeholder="{{form.post_text.label}}" >-->
    <textarea type="text" id='id_post_text' name="post_text"class="form-control"  placeholder="{{form.post_text.label}}"></textarea>
  </div>

   <div class="form-group col-md-10">
    <button type="submit" class="save btn btn-default">add post</button>
  </div>
{{form.errors}}
    </form>
 {% endblock %}
</html>

myblog/blogApp/templates/blogApp/detail.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'blogApp/bootstrap.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'blogApp/jquery-3.0.0.min.js' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'blogApp/bootstrap-theme.min.css' %}" />

{%include "blogApp/top4ik.html"%}

<div class="container">
<h1>
{{this_post.post_head}}
</h1>
<dl class="dl-horizontal">
  <dt>Author</dt>
  <dd>{{this_post.post_author}} </dd>
        <dt>Post Date</dt>
  <dd>{{this_post.post_date}}</dd>
    <dt>Post</dt>
  <dd> <div class="panel panel-default">
  <div class="panel-body">
    {{this_post.post_text}}
  </div>
</div>
      </dd>
</dl>
<ul>
     <body>Comments: </body>
{% if this_comments %}
    {% for comment in this_comments %}
    <hr>
    <dl class="dl-horizontal">
        <dt>Comment author</dt>
          <dd> {{ comment.comment_author }}, &nbsp; <strong> date: </strong> {{comment.comment_date}}</dd>
        <dt>Comment</dt>
        <dd> <div class="panel panel-default">
          <div class="panel-body">{{ comment.comment_text }}</div>
            </div>
        </dd>
    </dl>
    {% endfor %}
    </ul>
{% else %}
    <p>No comments are available.</p>
{% endif %}
</ul>
{% block content %}
<form method="post" class="comment-form">{% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="save btn btn-default">add comment</button>
</form>
{% endblock %}
</div>

myblog/blogApp/templates/blogApp/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'blogApp/bootstrap.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'blogApp/jquery-3.0.0.min.js' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'blogApp/bootstrap-theme.min.css' %}" />
<style>
   hr {
       width: 130px;
    border: none; /* Убираем границу */
    background-color: #6b6868; /* Цвет линии */
    color: rgba(63, 66, 61, 0.97); /* Цвет линии для IE6-7 */
    height: 2px; /* Толщина линии */
   }
  </style>

{% block content %}
<nav class="navbar navbar-inverse">
<ul class="nav navbar-nav">
  <li role="presentation" class="active"><a href="{% url 'blog:index' %}">Home</a></li>
  <li role="presentation"><a href="{%url 'blog:add_post' %}">Add Post</a></li>
</ul>
</nav>

    <div id="post" class="container" align="center">
        {%for post in posts%}
        <div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading"><a href="{% url 'blog:detail' post.id %}">{{ post.post_head }}</a></div>
  <div class="panel-body">
    <p>{{ post.post_text|truncatewords:30|safe  }}</p>
  </div>
  <!-- List group -->
  <ul class="list-group">
    <li class="list-group-item">Author: {{post.post_author}},  &nbsp;date: {{ post.post_date }}</li>
    <li class="list-group-item">comments : {{ post.comments_set.count }}</li>
      <hr>

  </ul>
            {%endfor%}
</div>
         <!--<table class="table">-->
    <!--<thead>-->
      <!--<tr>-->
        <!--<th>Post head</th>-->
        <!--<th>text post</th>-->
        <!--<th>count comments</th>-->
      <!--</tr>-->
    <!--</thead>-->

    <!--<tbody>-->
    <!--{%for post in posts%}-->
      <!--<tr>-->
        <!--<td><a href="{% url 'blog:detail' post.id %}">{{ post.post_head }}</a></td>-->
        <!--<td>{{ post.post_text|truncatewords:3|safe  }}</td>-->
        <!--<td>{{ post.comments_set.count }}</td>-->
      <!--</tr>-->
    <!--{%endfor%}-->
    <!--</tbody>-->
  <!--</table>-->


    <div id="pages" align="center">
        {% if posts.has_previous %}
            <a href="?page={{ posts.previous_page_number }}">Previous</a>
        {% endif %}
    <span class="current">
        Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
    </span>
        {% if posts.has_next %}
            <a href="?page={{ posts.next_page_number }}">Next</a>
        {% endif %}
    </div>
    </div>
{% endblock %}

myblog/blogApp/templates/blogApp/successful.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'blogApp/bootstrap.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'blogApp/jquery-3.0.0.min.js' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'blogApp/bootstrap-theme.min.css' %}" />

<div class="alert alert-success" role="alert">You'r post is sended to admin</div>

<div class="jumbotron">
  <p><a class="btn btn-primary btn-lg"  href="{% url 'blog:index' %}" role="button">Back</a></p>
</div>

myblog/blogApp/templates/blogApp/top4ik.html
<nav class="navbar navbar-inverse">
<ul class="nav navbar-nav">
  <li role="presentation" class="active"><a href="{% url 'blog:index' %}">Home</a></li>
  <li role="presentation"><a href="{%url 'blog:add_post' %}">Add Post</a></li>
</ul>
</nav>